### ISSUE TITLE
i cant play the mod anymore

### ISSUE THREAD

**Issue by FunkyPotao** [EyeOfDarkness/FlameOut#1]
i cant play the mod anymore, i got sent to a sacrofize tempel, i tried deleting the mod and reinstalling it but if i relaunch with the mod it brings me back to the sacrofize tempel.

**Comment by EyeOfDarkness** [comment]
what the hell are you talking about?

**Comment by FunkyPotao** [comment]
> what the hell are you talking about?

![image](https://github.com/EyeOfDarkness/FlameOut/assets/108956899/00e98b23-15b9-440e-969b-e50ec22be659)

this

**Comment by EyeOfDarkness** [comment]
![image](https://github.com/EyeOfDarkness/FlameOut/assets/64228877/89290d9c-bf7b-475c-8153-b503fd0597f0)
image is not loading.

**Comment by FunkyPotao** [comment]
> ![image](https://private-user-images.githubusercontent.com/64228877/296925543-89290d9c-bf7b-475c-8153-b503fd0597f0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTY4NTYsIm5iZiI6MTcwNTQxNjU1NiwicGF0aCI6Ii82NDIyODg3Ny8yOTY5MjU1NDMtODkyOTBkOWMtYmY3Yi00NzVjLTgxNTMtYjUwM2ZkMDU5N2YwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE0NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiOTk1YzE3Y2VmZTJlNmEyYWQ2NjdhYTg5YjQ2YmI2ZGI1ZWIzNjUyMTZiMDA2MTk4YzJmNjUyNDkwZGIyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rHWZ4wR1VK5AVZ_LjRd_rXUwuDEQmmyIL-fh6obmBpI) image is not loading.

![image](https://github.com/EyeOfDarkness/FlameOut/assets/108956899/bc9b5872-d92e-441e-9f16-0d3f981d786e)
 

there u go if the img still doesnt work try this


https://cdn.discordapp.com/attachments/980539898484367380/1195399107670446150/image.png?ex=65b3d92c&is=65a1642c&hm=18730223443697f6639c5ffcb86d45563d8332c71dff465d0bcffc03d4a9d1b2&

**Comment by FunkyPotao** [comment]
if both img doesnt load well theres basically a little mindustry corridor where there are png pray hands are on the side and you can pick a unit, if u pick a unit it dies in blood

**Comment by FunkyPotao** [comment]
oh i see how it is lol

**Comment by FunkyPotao** [comment]
found a way out dw about it anymor
